# Generated by Django 4.2.3 on 2023-09-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rta_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="receiver",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
